name: manga_list
description: Um aplicativo para rastrear mangás lidos, com filtros e ordenação.
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"  # Usa modo legacy para Android
  ios: false
  image_path: "assets/icon/icon.png"  # Caminho da sua imagem
  adaptive_icon_background: "#000000"  # Fundo preto (ajuste se necessário)
  adaptive_icon_foreground: "assets/icon/icon.png"  # Imagem principal